version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pubsub_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: pubsub_redis
    restart: always
    ports:
      - "6380:6379"

  app:
    build: .
    container_name: pubsub_app
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    command: ["npm", "run", "start"]

volumes:
  postgres_data:
